version: '3.9'

services:
  restart:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./web/restart:/var/www/html/restart
      - ./web/restart.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    volumes:
      - ./web/restart:/var/www/html/restart
      - ./web/foquz:/var/www/html/foquz
      - ./web/change_lease:/var/www/html/change_lease

  foquz:
    image: nginx:latest
    ports:
      - '8081:80'
    volumes:
      - ./web/foquz:/var/www/html/foquz
      - ./web/foquz.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  mikrotik-app:
    build:
      context: ./mikrotik
      dockerfile: ./Dockerfile.mikrotik
    ports:
      - '5000:5000'
    environment:
      - LOGIN=login
      - PASSWORD=pass
      - TZ=Europe/Moscow

  reverse-proxy:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./reverse-proxy/data:/data
      - ./reverse-proxy/letsencrypt:/etc/letsencrypt
  
  lease:
    image: nginx:latest
    ports:
      - '8082:80'
    volumes:
      - ./web/change_lease:/var/www/html/change_lease
      - ./web/change_lease.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: login
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: login
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://login:pass@mongo:27017/
      ME_CONFIG_BASICAUTH: false
